### ISSUE TITLE
Add "read more" link to excerpts

### ISSUE THREAD

**Issue by jomei** [thelehhman/plainwhite-jekyll#56]
Hi!
Currently on the posts page it's not obvious that an excerpt is not a full post. I think it would be nice to have some way to add some kind of "read more" link with custom text.

**Comment by DotIN13** [comment]
You could fork the repo and add your own `Read More` button.

You need to modify `_layout/home.html: 53`, for example as follows:
```html
<div class="post">
{%- if site.show_excerpts -%}
{{ post.excerpt }}
{%- endif -%}
<a class="read-more-link" href="{{ post.url | relative_url }}">Read More</a>
</div>
```

and `_sass/plain.scss` as follows
```css
.post {

  .read-more-link {
    font-family: Raleway, sans-serif;
    margin-bottom: 1em;
  }

  p {
    margin-bottom: 0.25rem;
  }
}
```

![tEWQB9.png](https://s1.ax1x.com/2020/05/27/tEWQB9.png)
