### ISSUE TITLE
[Question] How to setup dark mode toggle button?

### ISSUE THREAD

**Issue by amadeu01** [thelehhman/plainwhite-jekyll#61]
I added the ` dark_mode: true` flag, but it seems that it didn't work, does this have anything to do with other plugins? Do I need an extra step to properly setup?

```
base-url: /til
title: Today I Learned by Amadeu
description: This is a collection of concise write-ups of small things I've learned day to day across a variety of languages and technologies.
plugins:
   - jekyll-mentions
   - jemoji
   - jekyll-redirect-from
   - jekyll-sitemap
   - jekyll-feed
   - jekyll-seo-tag
   - jekyll-sitemap
   - jekyll-avatar
   - jekyll-include-cache
collections:
  tils:
    output: true
  ios:
    output: true
  swift:
    output: true
  rxjava:
    output: true
  android:
    output: true
  ios-macos:
    output: true
  design-patterns:
    output: true
  algorithm:
    output: true
remote_theme: thelehhman/plainwhite-jekyll
plainwhite:
  name: Amadeu Cavalcante
  tagline: Mobile Developer.
  date_format: "%-d of %b, %Y"
  search: true
  dark_mode: true

  social_links:
    twitter: amadeucavalcant
    github: amadeu01
    linkedIn: in/amadeu01

```

Am I doing anything wrong ?
